# Generated by Django 4.0.4 on 2022-05-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('show_cpus', models.BooleanField(default=True)),
                ('show_memory', models.BooleanField(default=True)),
                ('show_disk', models.BooleanField(default=True)),
                ('disabled', models.BooleanField(default=False)),
                ('frequency', models.IntegerField(default=1)),
            ],
        ),
    ]
