# Generated by Django 4.0.4 on 2022-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0002_sensor_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='NoName', max_length=30),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(default='NoName', max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='NoName', max_length=30),
        ),
    ]
