# Generated by Django 4.0.4 on 2022-08-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0003_client_name_alter_dashboard_name_alter_sensor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='availableGPIOPins',
            field=models.CharField(default='[2, 3, 4, 14, 15, 17, 18, 27, 22, 23, 24, 10, 9, 25, 11, 8, 7, 5, 6, 12, 13, 19, 16, 26, 20, 21]', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='availablePins',
            field=models.CharField(default='[3, 5, 7, 8, 11, 12, 13, 15, 16, 18, 19, 21, 22, 23, 24, 26, 29, 31, 32, 33, 35, 36, 37, 38, 40]', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='boardType',
            field=models.CharField(choices=[('Raspberry Pi 2B', 'Raspberry Pi 2B'), ('Banana Pro', 'Banana Pro'), ('ESP32', 'ESP32')], default='Raspberry Pi 2B', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='enabledSensors',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='pinConfig',
            field=models.CharField(default='{}', max_length=256),
        ),
        migrations.AddField(
            model_name='client',
            name='usedPins',
            field=models.CharField(default='[]', max_length=100),
        ),
    ]
