# Generated by Django 4.0.4 on 2022-08-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0004_client_availablegpiopins_client_availablepins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=30)),
                ('boardType', models.CharField(choices=[('Raspberry Pi 2B', 'Raspberry Pi 2B'), ('Banana Pro', 'Banana Pro'), ('ESP32', 'ESP32')], default='Raspberry Pi 2B', max_length=20)),
                ('boardImageUrl', models.CharField(default='https://www.bigmessowires.com/wp-content/uploads/2018/05/Raspberry-GPIO.jpg', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='boardType_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartHome.boardtype'),
        ),
    ]
