# Generated by Django 4.0.4 on 2022-08-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0005_boardtype_client_boardtype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='boardType_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='boardType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartHome.boardtype'),
        ),
    ]
