# Generated by Django 4.0.4 on 2022-08-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0006_remove_client_boardtype_id_alter_client_boardtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pinConfig',
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('1-channel-relay', 'Relay'), ('8-channel-relay', 'Relay-8'), ('IRSensor', 'IRSensor'), ('TemperatureSensorDallas', 'TemperatureSensorDallas'), ('TemperatureSensorDH11', 'TemperatureSensorDH11'), ('HumiditySensor', 'HumiditySensor'), ('RFIDSensor', 'RFIDSensor'), ('CO2Sensor', 'CO2Sensor')], default='Raspberry Pi 2B', max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GPIOPinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pins', models.CharField(max_length=256)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartHome.client')),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartHome.sensor')),
            ],
        ),
    ]
