# Generated by Django 4.0.4 on 2022-08-14 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0007_remove_client_pinconfig_sensor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartHome.client'),
        ),
    ]
