# Generated by Django 4.0.4 on 2022-08-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0009_rename_client_id_gpiopinconfig_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='availableGPIOPins',
            field=models.JSONField(default=[2, 3, 4, 14, 15, 17, 18, 27, 22, 23, 24, 10, 9, 25, 11, 8, 7, 5, 6, 12, 13, 19, 16, 26, 20, 21], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='availablePins',
            field=models.JSONField(default=[3, 5, 7, 8, 11, 12, 13, 15, 16, 18, 19, 21, 22, 23, 24, 26, 29, 31, 32, 33, 35, 36, 37, 38, 40], max_length=100),
        ),
        migrations.AlterField(
            model_name='gpiopinconfig',
            name='pins',
            field=models.IntegerField(max_length=2),
        ),
    ]
