# Generated by Django 4.0.4 on 2022-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0011_rename_sensor_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpiopinconfig',
            name='inputType',
            field=models.CharField(choices=[('pull_up', 'pull_up'), ('pull_down', 'pull_down')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gpiopinconfig',
            name='type',
            field=models.CharField(choices=[('1-channel-relay', 'Relay'), ('8-channel-relay', 'Relay-8'), ('IRSensor', 'IRSensor'), ('TemperatureSensorDallas', 'TemperatureSensorDallas'), ('TemperatureSensorDH11', 'TemperatureSensorDH11'), ('HumiditySensor', 'HumiditySensor'), ('RFIDSensor', 'RFIDSensor'), ('CO2Sensor', 'CO2Sensor')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='usedPins',
            field=models.JSONField(default=[], max_length=100),
        ),
    ]
