# Generated by Django 4.0.4 on 2022-08-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0012_gpiopinconfig_inputtype_gpiopinconfig_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpiopinconfig',
            name='module',
        ),
        migrations.AddField(
            model_name='module',
            name='used_pins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartHome.gpiopinconfig'),
        ),
    ]
