# Generated by Django 4.0.4 on 2022-08-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0018_alter_client_availablepins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='availableGPIOPins',
            field=models.JSONField(default=list, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='availablePins',
            field=models.JSONField(default=list, max_length=100),
        ),
    ]
