# Generated by Django 4.0.4 on 2022-08-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0020_remove_module_used_pins_gpiopinconfig_module_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpiopinconfig',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RemoveField(
            model_name='gpiopinconfig',
            name='client',
        ),
        migrations.AddField(
            model_name='gpiopinconfig',
            name='pinModuleNumber',
            field=models.IntegerField(null=True),
        ),
    ]
