# Generated by Django 4.0.4 on 2022-08-16 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0021_rename_module_id_gpiopinconfig_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='enabledSensors',
        ),
        migrations.AlterField(
            model_name='client',
            name='boardType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_type', to='SmartHome.boardtype'),
        ),
        migrations.AlterField(
            model_name='module',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configured_modules', to='SmartHome.client'),
        ),
    ]
