# Generated by Django 4.0.4 on 2022-08-16 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0022_remove_client_enabledsensors_alter_client_boardtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardtype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='usedPins',
        ),
        migrations.AddField(
            model_name='gpiopinconfig',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_used_pins', to='SmartHome.client'),
        ),
    ]
