# Generated by Django 4.0.4 on 2022-08-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0023_remove_boardtype_name_remove_client_usedpins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpiopinconfig',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='SmartHome.client'),
        ),
    ]
