# Generated by Django 4.0.4 on 2022-08-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0024_alter_gpiopinconfig_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1-channel-relay', 'Relay'), ('8-channel-relay', 'Relay-8'), ('IRSensor', 'IRSensor'), ('TemperatureSensorDallas', 'TemperatureSensorDallas'), ('TemperatureSensorDH11', 'TemperatureSensorDH11'), ('HumiditySensor', 'HumiditySensor'), ('RFIDSensor', 'RFIDSensor'), ('CO2Sensor', 'CO2Sensor'), ('Led-Output', 'LedOutput')], default='Raspberry Pi 2B', max_length=30)),
                ('power_pins', models.IntegerField(default=1, null=True)),
                ('ground_pins', models.IntegerField(default=1, null=True)),
                ('signal_pins', models.IntegerField(default=1, null=True)),
                ('inputType', models.CharField(choices=[('pull_up', 'pull_up'), ('pull_down', 'pull_down')], default=None, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gpiopinconfig',
            name='inputType',
        ),
        migrations.RemoveField(
            model_name='gpiopinconfig',
            name='type',
        ),
        migrations.AddField(
            model_name='client',
            name='gpio_mode',
            field=models.CharField(choices=[('None', 'None'), ('pull_up', 'pull_up')], default='Raspberry Pi 2B', max_length=20),
        ),
        migrations.AlterField(
            model_name='gpiopinconfig',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_used_pins', to='SmartHome.client'),
        ),
        migrations.CreateModel(
            name='ConfiguredModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('pins', models.CharField(max_length=30)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configured_modules', to='SmartHome.client')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_modules', to='SmartHome.availablemodule')),
            ],
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartHome.configuredmodule'),
        ),
        migrations.AlterField(
            model_name='gpiopinconfig',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_pins', to='SmartHome.configuredmodule'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
