# Generated by Django 4.0.4 on 2022-08-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0025_availablemodule_remove_gpiopinconfig_inputtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuredmodule',
            name='pins',
        ),
    ]
