# Generated by Django 4.0.4 on 2022-08-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0026_remove_configuredmodule_pins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='availableGPIOPins',
        ),
        migrations.RemoveField(
            model_name='client',
            name='availablePins',
        ),
        migrations.AddField(
            model_name='boardtype',
            name='availableGPIOPins',
            field=models.JSONField(default=[2, 3, 4, 14, 15, 17, 18, 27, 22, 23, 24, 10, 9, 25, 11, 8, 7, 5, 6, 12, 13, 19, 16, 26, 20, 21], max_length=100),
        ),
        migrations.AddField(
            model_name='boardtype',
            name='availablePins',
            field=models.JSONField(default=[3, 5, 7, 8, 11, 12, 13, 15, 16, 18, 19, 21, 22, 23, 24, 26, 29, 31, 32, 33, 35, 36, 37, 38, 40], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='gpio_mode',
            field=models.CharField(choices=[('None', 'None'), ('pull_up', 'pull_up')], default='None', max_length=20),
        ),
    ]
