# Generated by Django 4.0.4 on 2022-08-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0027_remove_client_availablegpiopins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpiopinconfig',
            name='type',
            field=models.CharField(choices=[('power', '+'), ('ground', '-'), ('signal', '$'), ('i2c', 'i²c')], default='None', max_length=20),
        ),
    ]
