# Generated by Django 4.0.4 on 2022-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0028_gpiopinconfig_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpiopinconfig',
            name='type',
            field=models.CharField(choices=[('power', '+'), ('ground', '-'), ('signal', '$'), ('i2c', 'i²c')], default='signal', max_length=20),
        ),
    ]
